### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by ghost**
This submission is considerably more ambitious than the last. Headings were added to break up the text and call out individual topics and facts. A more complex table of contents was built from the headings. Portions of the text were adjusted slightly to accommodate the new organization, which included moving some text blocks for chronological or clarity reasons. (For example, I consolidated the extended discussions of some website "stories" to be adjacent to the initial summary of each story.) I removed the Isis-as-FBI-informant .jpg because it didn't contain the expected information. I added "Nick" to the section about the website. I also corrected at least one date.

### CODE REVIEW

**Comment by ghost** [comment]
If you like this latest update, I'm thinking that the next thing to do is unpack the references so that the original source and the date are easily discoverable. I'm thinking of superscript links and a list of notes along the lines of Wikipedia. This will make it very easy to adjust any remaining chronological puzzles, and it will allow readers to see the original sources without clicking first on a link to an archive.

**Comment by Enegnei** [comment]
I would definitely like to put in more headers since I've added some big paragraphs in the last few weeks and those need to be framed more. 

The reason the victims from the website were originally in list format was due to the lack of information at the time but I agree those should be broken up into paragraphs. However on that change I think I'm going to wait until after Tor releases their report. There are eight profiles on the website and according to Gizmodo, Tor only interviewed 6 women total (including witnesses, so not even 6 alleged victims) and they may not even be the same people as the website. What I'll do there is move "Sam" and "Forest" down into the paragraphs of Macrina and Lovecruft because like Farr they've revealed themselves publicly, and the non-public ones will stay on the list format. When Tor releases their report, whether the other alleged victims go public or not, there might be more information, so I'll considering making them into paragraphs as well.

I also like your idea about making the references more discoverable. The only problem with using original links as Wikipedia does is that in many cases here, pages have been changed or deleted completely. I try to make all my links go to an archived version so that I don't have to check back for link-rot (which in an open-source intelligence piece would be a nightmare unless I added a script to alert me to it). I've tried to make up for that with images here and there so it's not just plain text.

Due to the number of changes and branch conflict, I'm not going to merge this one, but I'll model my upcoming changes after this format you made and link back to it for credit. Thanks!

**Comment by ghost** [comment]
This all makes good sense. 

Concerning the references, I'm not thinking of actually copying the Wikipedia style, but of modifying it. WP insists on using vetted secondary sources as references, and archives don't really fit that requirement. When I made up a list of the leaked @ioerror documents on my own site, I came to the conclusion (as you did) that archives had to be used as insurance against the ephemeral nature of the original documents. WP would regard your timeline and my leak list as "original research," which is also not allowed. 

A WP reference to a news website (for example) has this structure, where "_XXX_" means linked text:

[ Author (Date). ]  [ _Title._ ] [ Site/publication name. ] [ Retrieval date. ]

I would suggest using something more like this:

[ Author (Date). ] [ _Title._ ("Archived [date])" ] [ Site/publication name.  ] [ "Source:" URL  ]

Where:
- Author may well be "Anonymous".
- _Title._ is linked to the archived location.
- URL is the original URL, spelled out and not hyperlinked.

This provides various advantages:
- The date of the actual publication is given if known.
- The link gives a name to the document and goes reliably to an archived version.
- The original URL is provided as historical metadata but there is no need to confirm that it works anymore.

Otherwise, the style could follow the bidirectional superscript style WP uses, which makes it easy to check a reference and then jump back to where you are reading.

**Comment by Enegnei** [comment]
That sounds good to me. I did something similar (not quite with that reference formatting though) in my Apple vs. FBI investigation, mirrored the vital documents elsewhere in the repository and then linked to them on the write-up page: https://github.com/Enegnei/AppleVsFBI/blob/master/AppleVsFBI.md#mirror-links. I'm open to doing the mirroring again here since any page archived with Archive.is is downloadable as a zip file, but the organisation of folders for all that in the repo would have to be planned in advance or it could get super messy.

**Pull request closed without merging**
