### PR TITLE
more details on my resignation from Tor.

### PR DESCRIPTION
**Pull request by virgil**

### CODE REVIEW

**Comment by Enegnei** [comment]
I will add your Medium post; however I would prefer to keep the link from your website as it gives a summary of your former role there. Also, all links in the investigation are archived versions for linkrot prevention & (sometimes) timestamping purposes. Revised edit would be the following:

> A few days later, he left the Tor Project over the issue and took down [his blog page on his work with Tor](https://web.archive.org/web/20160503124544/http://virgil.gr/tor/). On September 4th, he published a [Medium post](https://archive.fo/jCj46) to restate his objections and formally announce his resignation.

**Comment by virgil** [comment]
Sounds good.  Support.  FWIW I'll probably put-up my http://virgil.gr/tor page, just as "past" work.

**Comment by virgil** [comment]
I know my medium post is a little different from the typical Jake stuff, and if you have any comments on the Medium I am all ears.

**Comment by Enegnei** [comment]
I don't have enough context knowledge or experience with the aforementioned countries to comment on whether including a commitment to human rights in the Social Contract poses a risk - further, whether they would be culpable for that risk. If Tor was more obscure and hadn't already done a lot of outreach & presentations about how it can be a tool for that purpose, I'd be more inclined to say yes, but even then I'd place far more blame in the repressive government policies themselves than on Tor-the-company. At present I'm more concerned about their use of the term "Social Contract" in general, which I will probably share my thoughts on soon.

**Pull request closed without merging**
